### ISSUE TITLE
[3 Weeks] 

### ISSUE THREAD

**Issue by jak010** [Peneteam/_StudyRepo#6]
####  3주차
 - 참석 :  IT, K, 너굴
 - 2 Weeks Assign : IT, K

#### 실습 대상
 -  HackTheBox :  Luanne

#### Methodology
1. 정찰
- email, host, words, identify

2. Scan
- Nmap -> Port -> /weather -> Path Directory Bruteforcing

3. Gaining Access

#### Next Week
- User Privilige, Root Privilige
---
- 3 Weeks Assign
  - [x] Regist : K, 너굴 [HackTheBox 가입 후 댓글에 닉네임] 기재
  - [x] Scan Tool : Nmap, RustScan
  - [x] Directory BruteForcing : gobuster, dirb, ffuf
  - [x] 댓글에다 어떤 도구를 썻고 뭐가 더 편하지만 의견을 공유해주세요

**Comment by xoheon** [comment]
ppplaylist/505183

**Comment by king-raccoon** [comment]
kingRaccoon/505200

**Comment by NownS** [comment]
Nmap이 확실히 범용성 면에 있어서 쓰기 좋습니다. 레퍼런스도 많고, 다양한 스캔 기능을 지원하는 것 같네요.
dir bruteforce의 경우, 전반적으로 유사한 기능을 제공하는데 결국 중요한 점은 사전 파일인 듯 싶네요. 결국 사전 파일이 잘 구축되어 있을수록 좀 더 빠른 공격이 가능하고, 완탐의 경우는 비슷한 것 같습니다.
