### ISSUE TITLE
[4 weeks]

### ISSUE THREAD

**Issue by jak010** [Peneteam/_StudyRepo#8]
- 스터디 진행방식

**Comment by jak010** [comment]
- 참여자 : Nowns, K, IT
- 진행방식
  - 일주일 동안 공부한 내용을 리뷰하는 방식으로 진행
    - 공부한 내용은 사소하더라도 기록을 남기고 공유
  - 틀을 정하고 그 안에서 공부한 내용을 발표하는 방식
  - 사전에 공격기법 설명 후 문제 풀이 하는 방식으로

- `사전 조사` 하기
  - 침투 테스팅에 대한 사전 조사 후 공유 한 다음 리뷰 (PR, ISSUE 댓글)
  - `기본 지식`에 대한 고려

- `기본 지식`
  - 웹이 돌아가는 원리, 네트워크 개념, 프로그램이 돌아가는 원리 
  
### To-Do
1. 스터디 멤버분들이 어느 정도에 대한 지식을 가지고 있는지를 댓글에 작성 (본인 작성)
2. `웹이 돌아가는 원리`에 대해 사전조사 진행 후 댓글이나 PR 남기기

### 패널티
- 스터디 참여 제한 (특정 자료에 대한 열람 금지)
- 삼진 아웃제

**Comment by NownS** [comment]
프로그래밍 - 학교 공부를 통해 전반적인 컴퓨터과학 이론은 공부한 상태로 현재 웹 백엔드 구현 관련 토이프로젝트 진행중, 코딩테스트 준비중
보안 - 웹/시스템 해킹 기초 원리는 알고 있으나 실습은 아직 부족한 상태

**Comment by dlgytjd1997** [comment]
프로그래밍 - 여러 언어를 접해보고, 기초는 알고있지만 프로젝트 참여등 실습 상태는 미흡합니다.
보안 - 웹, 인프라 해킹 기초는 알고 있다고 생각합니다. 실습은 접해본적이 없습니다.

대략적으로 인프라나 웹 동작원리는 알고 있고 많이 접해보았지만, 코딩은 기초 문법 정도만 알고있는 수준입니다.

**Comment by xoheon** [comment]
프로그래밍 - C, JAVA 언어 등 , 기초만 알고있고 팀프로젝트를 해본적은 없습니다. 

보안 - 웹 해킹 기초원리를 알고있고 실습을 접해본적이 거의 없습니다. (CTF에서 문제 몇문제 푸는 정도)

**Comment by NownS** [comment]
https://nowns.tistory.com/3?category=919140
