### ISSUE TITLE
[ENV] Mac Fusion에서 HackTheBox 연결 문제

### ISSUE THREAD

**Issue by jak010** [Peneteam/_StudyRepo#9]
- Nowns
  - 맥 내부의 fusion에서 HackTheBox IP로 ping 전달이 안되는 문제 발생

- fusion version : 
- Mac OS version :

**Comment by NownS** [comment]
Fusion version : 12.1.0
Mac OS version : 11.1

해결 - Vmware fusion 내부에서 별도로 vpn 설정 필요, vm과 실제 네트워크 간 분리 운영되고 있었음, 맥의 경우 윈도우즈 vmware와 달리 네트워크 구조 상태를 확인하기 어렵기 때문에, 가상 머신을 별도의 PC처럼 운용하는 편이 좋을 것 같음.
